name: Deploy Manual Github Page
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Manual Github Page
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add Documents/Manual
          git commit -m "Initial Manual subtree commit"
          git push origin `git subtree split --prefix Documents/Manual master`:gh-pages --force