name: Upload manual to Github Page
on:
  push:
    branches:
      - master
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install pdoc3
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Generate updated Reference Manual
        run: |
          python create_weasel_manual.py

      - name: Deploy manual to Github Page https://qib-sheffield.github.io/Weasel/
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: Documents/Manual
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Reference Manual ${{ steps.date.outputs.date }}"