name: Create Weasel Executable
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' # install the python version needed
          
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip

      - name: Generate Executable
        run: python create_weasel_executable.py
